clear
dcBlockParams.filterOrder = 4;
dcBlockParams.passbandRipple = 0.1; 
dcBlockParams.stopbandAtten = 70; 
dcBlockParams.normalizedBandwidth = 0.001;

dcBlockFilt = designHighpassIIR( ...
    "FilterOrder", dcBlockParams.filterOrder, ... 
    "StopbandAttenuation", dcBlockParams.stopbandAtten, ...
    "SystemObject", true, ...
    "DesignMethod", "butter", ...
    "HalfPowerFrequency", dcBlockParams.normalizedBandwidth ...
    );

fvtool(dcBlockFilt);

%% unused
% dcBlockParams.filterOrder = 6;
% dcBlockParams.passbandRipple = 0.1; 
% dcBlockParams.stopbandAtten = 60; 
% dcBlockParams.normalizedBandwidth = 0.001;
% [z,p,k] = ellip(dcBlockParams.filterOrder, ... 
%   dcBlockParams.passbandRipple, ...
%   dcBlockParams.stopbandAtten, ... 
%   dcBlockParams.normalizedBandwidth);
% [sos,g] = zp2sos(z,p,k);
% [num, den] = sos2ctf(sos);
% dcBlockFilt = dsp.SOSFilter(num, den, "ScaleValues", g);
% fvtool(dcBlockFilt);